GET http://localhost:3000/api/v1/tours?duration=5&difficulty=easy    




GET http://localhost:3000/api/v1/tours



curl -s http://localhost:3000/api/v1/tours \
  -H "Authorization: Bearer <token>"
  